[package]
name = "sero"
version = "0.1.7"
edition = "2021"
description = "A simple and lightweight library for maintaining a shared store of locks."
license = "MIT"
repository = "https://github.com/mrvillage/sero"
documentation = "https://docs.rs/sero"

[dependencies]
dashmap = "5"
