[package]
name = "sero"
version = "0.1.1"
edition = "2021"
description = "A simple and lightweight library for maintaining a shared store of locks."
license = "MIT"
repository = "https://github.com/mrvillage/sero"

[dependencies]
dashmap = "5.0"
